---
apiVersion: v1
data:
  .dockerconfigjson: "{{ .Values.astraRegistrySecret }}"
kind: Secret
metadata:
  name: container-reg-credential
  namespace: {{ .Values.NamespaceAstraOperator }}
type: kubernetes.io/dockerconfigjson
