apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.astraRegistrySecret }} 
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets }}
  namespace: {{ .Values.NamespaceAstraOperator }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.astraRegistrySecret }}
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets }}
  namespace: {{ .Values.NamespaceAstraControl }}
type: kubernetes.io/dockerconfigjson
